### ISSUE TITLE
How to handle the issue of "org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver"?

### ISSUE THREAD

**Issue by cloudpractise** [SteelBridgeLabs/neo4j-gremlin-bolt#102]
When I  pilot run this project and try to access Neo4J via  Java code, I face the issue of  "org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver"?

Any big hands are highly appreciated. TIA. 

1. The enviorments: 
- OS: Mac OS Catalina 10.15.6 
- Java : 1.8.0_261
- Docker: 19.03.12

2. The installation steps: 
a. git clone this project
b. sudo docker run -d --name neo4j -p 7687:7687 -p 7474:7474 -e NEO4J_AUTH=neo4j/neo4j123 -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:3.4-enterprise
c.   edit the code  which is shown at  the 3) the  java code: 
d. run the code and then get the error which is shown at  the 4) 4.  the IDEA console error log: 

3. The  java code: 
--
package com.steelbridgelabs.oss.neo4j.structure;

import com.steelbridgelabs.oss.neo4j.structure.providers.DatabaseSequenceElementIdProvider;
import com.steelbridgelabs.oss.neo4j.structure.providers.Neo4JNativeElementIdProvider;
import org.apache.tinkerpop.gremlin.structure.Graph;
import org.apache.tinkerpop.gremlin.structure.Transaction;
import org.apache.tinkerpop.gremlin.structure.Vertex;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;

public class app {

    public static void main(String[] args) {

        Driver driver = GraphDatabase.driver("bolt://localhost", AuthTokens.basic("neo4j", "neo4j123"));
        Neo4JElementIdProvider edgeIdProvider = new DatabaseSequenceElementIdProvider(driver);
        Neo4JElementIdProvider vertexIdProvider = new DatabaseSequenceElementIdProvider(driver);

        try {
            try (Graph graph = new Neo4JGraph(driver, "graph.db", vertexIdProvider, edgeIdProvider)) {
                // begin transaction
                try (Transaction transaction = graph.tx()) {
                    // use Graph API to create, update and delete Vertices and Edges
                    Vertex vertex = graph.addVertex("name", "John", "age", 50);
                    // commit transaction
                    transaction.commit();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
--- 

4.  the IDEA console error log: 
-----
Information: Direct driver instance 1439337960 created for server address localhost:7687
org.neo4j.driver.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:98)
	at org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:92)
	at com.steelbridgelabs.oss.neo4j.structure.Neo4JSession.beginTransaction(Neo4JSession.java:109)
	at com.steelbridgelabs.oss.neo4j.structure.Neo4JGraph$Neo4JTransaction.doOpen(Neo4JGraph.java:70)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.open(AbstractTransaction.java:95)
	at org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:207)
	at org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR$1.accept(Transaction.java:204)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractThreadLocalTransaction.doReadWrite(AbstractThreadLocalTransaction.java:92)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.readWrite(AbstractTransaction.java:131)
	at com.steelbridgelabs.oss.neo4j.structure.Neo4JGraph.addVertex(Neo4JGraph.java:541)
	at com.steelbridgelabs.oss.neo4j.structure.app.main(app.java:25)
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.async.connection.HandshakeHandler.protocolNoSupportedByServerError(HandshakeHandler.java:164)
		at org.neo4j.driver.internal.async.connection.HandshakeHandler.handleUnknownSuggestedProtocolVersion(HandshakeHandler.java:145)
		at org.neo4j.driver.internal.async.connection.HandshakeHandler.decode(HandshakeHandler.java:118)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

**Comment by rjbaucells** [comment]
What version of this library are you using? I can confirm the latest version can connect to Neo4J 3.5 and 4.0 without any problems.
